### ISSUE TITLE
What's the meaning of the file voc_dims.txt?

### ISSUE THREAD

**Issue by zhengshoujian** [cersar/3D_detection#3]
Hi, could you tell me what's the meaning of the array in voc_dims.txt? How do you get the result?

**Comment by cersar** [comment]
Each row is one class's average dim corresponding to classes in the voc_class.txt.It is caculated by count each class's average dim in the voc lable files.

**Comment by jkstyle2** [comment]
@cersar , I'm wondering why you use the dimension of voc datasets. As we're training with the kitti dataset, i think we have to calculate the dimension from the kitti, not the voc.
Could you share your idea? thanks.
