### ISSUE TITLE
There is a error when i try the project

### ISSUE THREAD

**Issue by zhengshoujian** [cersar/3D_detection#6]
when i download your pretrained weights file, and run the detection.py, there is a error, which is "Dimension 1 in both shapes must be equal, but are 4 and 12. Shapes are [256,4] and [256,12]. for 'Assign_99' (op: 'Assign') with input shapes: [256,4], [256,12]." what i do with the error? thanks a lot!

**Comment by cersar** [comment]
Did this error happen in the detection period?

**Comment by cersar** [comment]
@zhengshoujian I updated the model, have you tried the latest one?

**Comment by zhengshoujian** [comment]
@cersar do you mean the weights file with the link" http://ddl.escience.cn/f/RRk0", yeap, i just used the weights file and the error happen in the detection period.

**Comment by cersar** [comment]
@zhengshoujian Have you tried the latest code?

**Comment by zhengshoujian** [comment]
@cersar yes

**Comment by cersar** [comment]
@zhengshoujian I tried again, it works well for me, sorry for having no idea about your problem.

**Comment by zhengshoujian** [comment]
@cersar Ok,thanks a lot, i'll try again.

**Comment by xueyingliu** [comment]
@zhengshoujian You can check the ''bin_num'', looks like you changed this parameter.
