### ISSUE TITLE
Can you explain about post_processing.py ?

### ISSUE THREAD

**Issue by jkstyle2** [cersar/3D_detection#9]
First, thanks for your great work @cersar . It's really worth following rather than any other's work.

I've been trying to understand your intentions and most of the codes, and it's very readable and easy to follow.
One thing I have difficulty to understand is, the `compute_center()` in post_processing.py.
Can you please comment on some core lines that each line indicates for?

I really need your help, looking forward to getting your reply.
Thanks in advance!

**Comment by cersar** [comment]
@jkstyle2 Hi, jkstyle2, in `compute_center()`,  `inds` is the points for calculating the best coordinate , according to the paper, I choose the following points: 

![points1](https://user-images.githubusercontent.com/9484017/54065893-ee5f6180-4261-11e9-8cfd-742a6802217f.jpg)

the method is from the paper SupplementaryMaterial, 
![supple](https://user-images.githubusercontent.com/9484017/54065458-501ccd00-425c-11e9-9116-9b5137c8eccb.PNG)
and here is my derivation:
![cnter](https://user-images.githubusercontent.com/9484017/54065695-932c6f80-425f-11e9-946c-ba6fd9e0cc7a.jpg)

**Comment by xueyingliu** [comment]
@jkstyle2 
Hi, jkstyle2, in `compute_center()`,  `inds` is the points for calculating the best coordinate , according to the paper, I choose the following points, that means I choose xmax and xmin from [1, 3, 5, 7] and choose ymax and ymin from [0, 1, 2, 3] : 
![points1](https://user-images.githubusercontent.com/30819873/54614563-99102500-4a97-11e9-8940-7a18507ef810.jpg)
the method is from the paper SupplementaryMaterial, 
![supple](https://user-images.githubusercontent.com/30819873/54614728-db396680-4a97-11e9-9e7d-85cf6881fff3.PNG)
and here is my derivation:
![center_l](https://user-images.githubusercontent.com/30819873/54614622-af1de580-4a97-11e9-95b3-4c6503b3947b.jpg)
and how to get the `theta_ray`:
![theta](https://user-images.githubusercontent.com/30819873/54614800-f7d59e80-4a97-11e9-8538-1ee9faf89cb4.jpg)
